### ISSUE TITLE
Modify Docker workflow to push on specific variable

### ISSUE THREAD

**Issue by thefaftek-git** [thefaftek-git/CA_Scanner#149]
# Modify Docker Workflow to Push to Docker Hub When Specific Variable is Set

## Description

Currently, the Docker build and push workflow (`.github/workflows/docker-build.yml`) only triggers on pushes to the main branch. We need to modify this workflow so that it also pushes to Docker Hub when a specific environment variable is set in any branch.

This will allow us to manually trigger Docker builds for other branches by setting an appropriate variable, without having to merge code into main first.

## Why is this important?

1. **Flexibility**: Allows building and pushing Docker images from non-main branches when needed
2. **Faster Iteration**: Enables testing of Dockerized applications in different environments without waiting for a merge
3. **Improved Workflow**: Supports feature branch development with Docker-based testing and validation

## Implementation Plan

1. Update `.github/workflows/docker-build.yml` to trigger on any push or pull request, not just main
2. Add conditional logic to only build and push when:
   - The branch is main OR
   - A specific environment variable (e.g., `PUSH_DOCKER_IMAGE`) is set to "true"
3. Test the updated workflow with different scenarios (main branch, feature branches with/without the variable)
4. Document the change in the README and CI/CD documentation

### Update triggers to include all branches:
```yaml
tests: 10
  push:
    branches:
      - "**"
    paths:
      - "Dockerfile"
      - "ConditionalAccessExporter/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "Dockerfile"
      - "ConditionalAccessExporter/**"
```

### Add conditional logic to the build step:
```yaml
tests: 20
- name: Build and push Docker image
  if: github.ref == refs/heads/main || env.PUSH_DOCKER_IMAGE == true
  run: |
    docker build -t ${{ secrets.DOCKER_USERNAME }}/ca-scanner:latest .
    docker tag ${{ secrets.DOCKER_USERNAME }}/ca-scanner:latest ${{ secrets.DOCKER_USERNAME }}/ca-scanner:${{ github.sha }}
    docker push ${{ secrets.DOCKER_USERNAME }}/ca-scanner:latest
    docker push ${{ secrets.DOCKER_USERNAME }}/ca-scanner:${{ github.sha }}
```

### Add similar condition to the multi-architecture build step:
```yaml
tests: 30
- name: Build multi-architecture image
  if: github.ref == refs/heads/main || env.PUSH_DOCKER_IMAGE == true
  run: |
    docker buildx create --use
    docker buildx inspect --bootstrap
    docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/ca-scanner:multiarch-latest --push .
```

## Additional Considerations

- We may need to update the GitHub Actions runner configuration to ensure environment variables are properly passed
- Consider adding documentation on how to set this variable in pull requests or branch pushes
- Ensure that the Docker Hub credentials have appropriate permissions for pushing from non-main branches

## Next Steps

1. Implement the proposed changes to `.github/workflows/docker-build.yml`
2. Test the workflow with different scenarios
3. Update documentation as needed
4. Close this issue once the implementation is verified and working correctly
